version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executors:
      name: node/default
      browsers:
        docker:
          - image: circleci/node:browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm lint
            - run: npm run build:ssr
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
