version: 2.1
jobs:
  build:
    working_directory: ~/news
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run lint
      - run: xvfb-run -a npm run test --no-progress --browsers=ChromeNoSandbox
