version: 2.1
jobs:
  build:
    working_directory: ~/news
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - setup_remote_docker


      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run lint
      - run: xvfb-run -a npm run build:ssr
      - run: xvfb-run -a npm run test --no-progress --browsers=ChromeNoSandbox
      - run:
          command: |
                  docker build -t registry.heroku.com/$APP_NAME/web .
      - run:
          command: |
                  docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          command: |
                  docker push registry.heroku.com/$APP_NAME/web:latest
