version: 2.1
orbs:
  angular: okode/angular@1.0.67
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm lint
            - run: npm run build:ssr
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
